[interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = 4AdoeJ9NtepRaHYNonqOIHiDhbFIyqOjXBiJcMaFgEQ=

[Peer]
PublicKey = zpR+tmZ5FEFXofMmlAAlBkgCG4vtpCsct1sGnr/vuh8=
AllowedIPs = 10.0.0.2/32
