server {
listen 443 ssl;
server_name ztna.lab;

# server certificate
ssl_certificate    /certs/server.crt;
ssl_certificate_key     /certs/server.key;

# mTLS - require and verify client cert
ssl_client_certificate    /certs/ca.crt;
ssl_verify_client     on;

# Pass identity headers to backend 
proxy_set_header X-Client-CN-      $ssl_ssl_client_s_dn_cn;
proxy_set_header X-Client-Verified $ssl_client_verify;

location /service-b/ {
    proxy_pass http://service-a:8080/;
 }

location /service-b/ {
    proxy_pass http://service-b:8080/;
 }
}
